Updated dependencies (until Nimble gets SPM stable) Updated build scripts
Update Travis build matrix
Cache Homebrew
Travis
Update Package.swift
Update Package.swift
Update .travis.yml
Update Package.swift
Fix minimum SPM version tool

Test

Rollback

Rollback

travis

Exclude tvos

Use master

Update Fastfile

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,22 +1,59 @@
 language: swift
-osx_image: xcode11.3
 if: tag is blank
 
 cache:
   bundler: true
   cocoapods: true
-
+  directories:
+    - $TRAVIS_BUILD_DIR/target
+    # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
+    - $HOME/Library/Caches/Homebrew
+    - /usr/local/Homebrew/
+    # used in OSX custom build script dealing with local bottle caching
+    - $HOME/local_bottle_metadata
 addons:
   homebrew:
     brewfile: true
     update: true
 
-script:
-- set -o pipefail
-- swift --version
-- rake
-- rake test
-- bundle exec fastlane pass_tests
-- bundle exec pod repo update
-- rake pods
-- bundle exec danger
+before_install: |
+  if [ -n "$IS_OSX" ]; then
+      TAPS="$(brew --repository)/Library/Taps"
+      if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
+          rm -rf "$TAPS/caskroom/homebrew-cask"
+      fi
+      find "$TAPS" -type d -name .git -exec \
+              bash -xec '
+                  cd $(dirname '\''{}'\'') || echo "status: $?"
+                  git clean -fxd || echo "status: $?"
+                  sleep 1 || echo "status: $?"
+                  git status || echo "status: $?"' \; || echo "status: $?"
+      brew_cache_cleanup
+  fi
+before_cache: |
+  # Cleanup dirs to be cached
+  set -e; set -x
+  if [ -n "$IS_OSX" ]; then
+      # When Taps is cached, this dir causes "Error: file exists" on `brew update`
+      if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
+          rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
+      fi
+      brew_cache_cleanup
+  fi
+  set +x; set +e
+
+jobs:
+  include:
+  - stage: Continuous Integration Coverage
+    name: SwiftPM macOS
+    os: osx
+    osx_image: xcode11.3
+    before_script:
+      - bundle install
+    script:
+      - set -o pipefail
+      - rake
+      - bundle exec fastlane pass_tests
+      - bundle exec pod repo update
+      - rake pods
+      - bundle exec danger
